### ISSUE TITLE
タグクラウドブロックをもう少しおしゃれにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/x-t9#112]
template-part/sidebar-post.html あたりにデフォルト配置してあるので、投稿アーカイブか投稿詳細ページで表示される

![更新情報-株式会社サンプル](https://user-images.githubusercontent.com/3272660/205841825-aabd552b-cc9a-424e-8f88-94f9e7d23739.png)

ブロックエディタ側で指定できる部分は極力ブロックエディタで指定してテーマにCSSをなるべく書かない方向で検討
※ 勿論なんともならない場合もあるので、無理だと思ったらCSS指定で可

参考

![スクリーンショット 2022-12-05 14 27 17](https://user-images.githubusercontent.com/3272660/205556280-64b03224-96fe-45c3-b90d-02814c02ecbd.png)

**Comment by sysbird** [comment]
@kurudrive 
ためしに タグクラウドブロックのカスタムCSS に書いてます
「極力ブロックエディタで指定して」を理解してないので、のちほど確認させてください

```
background: var(--wp--preset--color--bg-secondary) ;
color: var(--wp--preset--color--text-normal);

```
![tag](https://user-images.githubusercontent.com/4631838/216528583-f9f0c5d5-8965-4f7a-b673-1db989f79079.png)
