### ISSUE TITLE
輪郭だけのボタンでテキスト色がPrimary指定しているときホバーすると文字が見えなくなる

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/x-t9#116]
コアボタン
輪郭
テキスト色が Primary

下記デモサイトの下のほうにあるアウトラインボラン
https://demo.dev3.biz/x-t9/sample-design/

ホバー文字が見えない
ねんのため、プラグインなに使ってない状態でも発生

**Comment by sysbird** [comment]
デフォルトテーマでもこのような場合があるので、気にしなくてもよいかもしれないです

**Comment by kurudrive** [comment]
修正しました。まだ未リリースですが、
https://demo.dev3.biz/x-t9/sample-design/ にはアップしました。
↑で確認するか、master ブランチをプルしてビルドするか 
1.8.2 より後のバージョンがリリースされたら確認よろしくお願いいたします。
