### ISSUE TITLE
 アイキャッチの縦横比が固定なのは仕様でしょうか？

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/x-t9#121]
最近 x-t9 を触ってて、気になったのでメモです

アイキャッチに縦長画像を設定していても
`aspect-ratio: 320/180`
と固定の横長で表示されるのは仕様でしょうか？
どこかに設定ありますか？

私事ですが、お菓子袋(縦)をアイキャッチにしているような場合は向いてないのかな
x-t9 の仕様ということなら構わないです〜

**Comment by kurudrive** [comment]
あー・・・現状固定ですねー。うーむ、確かにこれは指定海上しつつ変更できる方法を考える必要がありますな...（・ｗ・；

**Comment by sysbird** [comment]
WordPress 6.3 で画像のアスペクト比をできるようになったので、表示できるようになりました！嬉しい
こちらは閉じます
