### ISSUE TITLE
【確認待ち】リストブロックのスタイルがデフォルトの時のみ、liの余白がなくなる。

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/x-t9#144]
テーマ側につけるのでしょうか、それともBlock側でしょうか？（[Lightningはテーマにliの余白がついているようでした）
スタイルが「デフォルト」の時だけ余白がなくなるようでしたので忘れないようissueにします。

**Comment by kurudrive** [comment]
たぶん↓でもう治ってるはず（・ｗ・

https://github.com/vektor-inc/x-t9/pull/164

vektor-inc とかで確認してみてくださいー。
