### ISSUE TITLE
【質問】カバーブロックの中のinner-containerは、横いっぱいに広がりますが、仕様でしょうか？

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/x-t9#178]
一応、カバーブロックの中身をグループブロックで囲えばコンテンツ幅におさまりますが、どうなのかなと思いissueをたてました
https://discord.com/channels/1010092469863587892/1010175825930367019/1101389508446011433

パターンでカバーブロックの中に入れているものもちょくちょくありまして、聞いてみました。

▼例えばこのパターン
https://patterns.vektor-inc.co.jp/vk-patterns/law_top/

---

Assigneesには石川さんをいれさせていただきました🙇‍♂️

**Comment by kurudrive** [comment]
@goutetsuguma @sysbird グループブロックで囲う運用でよろしくお願いいたします。

カバーの中を自動的にコンテンツ幅にするとそれを更に全幅にする処理がカオスになるのと、
ブロックテーマだと入れ子の要素を全幅にできなかったりするため。
