### ISSUE TITLE
見出しのフォントサイズが本文より小さくなる場合がある

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/x-t9#199]
やりたいこと → 見出し(コアの h3) がデフォルトでは大きめなので本文より少しだけ大きいぐらいにしたい
設定 → h3 のフォントサイズを 1.2 em にした

現象
【PC表示】 段落 16px に対して h2(1.2em) 17.652px
【モバイル表示】段落 14px に対して h2(1.2em)  12.6px ← 小さくなってる

再現してるページ
https://x-t9.vektor-inc.co.jp/delate-page (←非公開)

確認ようサンプル(コピーボタンが一番下にあります)
https://vk-block-test.vs4.nagoya/2023/07/03/heading-font-size/

theme.json/setting/typography/fluid をtrueにしているためらしい
→ 石川さんに連絡済み

**Comment by kurudrive** [comment]
@sysbird 修正版公開しました。
