### ISSUE TITLE
【相談】［VK ボタン］ボタンスタイル：ベタ塗りの白色、文字の色：カスタムカラーにした場合、hover時の文字色が白になるけど、良い方法があるのかどうか

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/x-t9#214]
あまり、このようなパターンは稀かもしれませんが、ボタンスタイル：ベタ塗りの白色、文字の色：カスタムカラーにした場合、hover時の文字色が白になります。文字の色をカスタムカラー以外にすれば問題ありませんので、テーマ側で直すのではなくカスタムCSSで直すのが良いのでしょうか？（テーマ側で対応するとしたら、背景色がプライムカラーの場合もあるので、その場合も考慮すると、Lightningテーマの様にhover時はちょっと背景が薄くなるくらいが良いのかなとも思ったけど、今更あまり変えられないですよね、、？）

![-X-T9-WordPress-Theme](https://github.com/vektor-inc/x-t9/assets/5525368/ce6236ad-a976-4dfe-ac81-58e5a47260af)

なぜ気になったかというと、パターンでたまたまそのようなボタンを作ったためです。でもいつもは白背景の塗りつぶしでカスタムカラーにすることは少なそうです。
https://patterns.vektor-inc.co.jp/vk-patterns/nursery-school_footer/

不要そうであればCloseしてください

**Comment by mtdkei** [comment]
@goutetsuguma @kurudrive
.vk_button .vk_button_link:hover の color: #fff を削除すればhover時にテキスト白にならなくなりました。(お問い合わせボタン参照)
![image](https://github.com/vektor-inc/x-t9/assets/21466284/e65310f3-1f19-4823-ad2f-71614b2b0754)

ただ、このCSSを書いている理由がなにかしらあるかもしれないので、プルリクを出すのを迷っています。
X-T9でVKボタンやコアのボタンの設定等は確認済みですが理由の特定には至ってません。

**Comment by mtdkei** [comment]
プルリクを確認しマージしましたのでissueをCloseします。ありがとうございました。
