### ISSUE TITLE
[ Site Logo Block] Image widthでの数値指定が効かない

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/x-t9#23]
### 環境
WordPress 5.9.2
X-T9 0.4.0

### 症状
Headerテンプレート内で Site Logo ブロックに画像を設定して、Image width にどんな数値を指定しても横幅が変わりませんでした。

### Editor画面：
<img width="1291" alt="スクリーンショット 2022-03-22 午後2 31 08" src="https://user-images.githubusercontent.com/43702482/159421936-5d3ef358-99a6-4ca7-93c6-84c50df2bd3e.png">

### フロントの様子：
![スクリーンショット 2022-03-22 午後2 35 47](https://user-images.githubusercontent.com/43702482/159422051-48a3d261-7176-4620-8e6b-c271d88e9389.png)

**Comment by kurudrive** [comment]
レイアウトが崩れないように
.site-logo--set .wp-block-site-logo クラスを指定してある場合に強制的に追加しているので一旦保留で（・ｗ・；

**Comment by kurudrive** [comment]
@ChiakiKouno こちら仕様変更で効くようになりましたー。

**Comment by ChiakiKouno** [comment]
ああっ　反応しておりませんで大変失礼しました🙇‍♀️　対応ありがとうございましたー！
