### ISSUE TITLE
X-T9 Pro クイックスタートのタイムゾーンが「UTC+0」になってました

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/x-t9#242]
ローカルでX-T9 Pro クイックスタートのデータをインポートしたら、タイムゾーンが「UTC+0」になってました。
![image](https://github.com/vektor-inc/x-t9/assets/21466284/b4a3df73-5c7a-4b1c-b63a-c0b6f43c57bb)

X-T9 Pro クイックスタートのデータを更新するときにこちらの更新もお願い致します。

※ 久納さんにも確認してもらっています。

**Comment by kurudrive** [comment]
@mtdkei ありがとうございましたー。修正版アップしましたー。
