### ISSUE TITLE
編集画面のみ、VKグリッドカラムカードブロック内にグループを入れると、幅が横幅いっぱいに広がらないかもしれない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/x-t9#248]
LightningやTT4では問題なく、X-T9の編集画面のみ、VKグリッドカラムカードブロック内にグループを入れると、横幅がいっぱいに広がらないのでいったんissueにします。

例えば以下のパターンをx-T9テーマの編集画面にコピペすると症状が確認できます
https://patterns.vektor-inc.co.jp/vk-patterns/nursery-school_flow-of-the-day/
![投稿を編集-“a”-‹-x-t9-—-WordPress](https://github.com/vektor-inc/x-t9/assets/5525368/31d0daab-92f4-440d-a8a6-325f536e2dbd)

**Comment by mtdkei** [comment]
@goutetsuguma 
確認したところ、私の環境でも、VKグリッドカラムカードブロック内にグループを入れた時に横幅がいっぱいに広がりませんでした。

**Comment by mtdkei** [comment]
プルリクがマージされましたのでCloseします
