### ISSUE TITLE
個別投稿で使っているカラムブロックのサイドバーの幅が変わらないです

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/x-t9#251]
## 現状
個別投稿で使っているカラムブロックの幅に数値を入れても変わりません。

## 現象の確認手順
1. [サイトエディター] > [テンプレート] > [個別投稿] に移動
2. 使われているメインカラムとサイドバーで使用しているカラムブロックの幅に数値を入れて更新
![image](https://github.com/vektor-inc/x-t9/assets/21466284/8661b335-493a-4056-ace3-c4f5b8327d2f)
3. フロントエンドで見るとサイドバーがgapを0にしているはずが余白が開いている状態になる
![image](https://github.com/vektor-inc/x-t9/assets/21466284/bcc576f3-575f-4348-b2e4-9f0d05c40fb7)

## 原因と思われる部分
サイドバーに使用されている以下のHTMLと
`<div class="wp-block-column is-style-main-layout-sidebar is-layout-flow wp-block-column-is-layout-flow" style="flex-basis:33.333%">`

以下のCSSがバッティングし、is-style-main-layout-sidebarの方が勝ってしまいます。

```
.is-style-main-layout-sidebar {
    flex-grow: unset !important;
    flex-basis: var(--wp--custom--layout--sidebar) !important;
}
```

![image](https://github.com/vektor-inc/x-t9/assets/21466284/7033ea6f-bd1e-42bc-a9ab-a2294c51ec96)

上記の原因は!importantかと思いますが、!importantを書いている理由があると思われるため、issueだけ上げておきました。

**Comment by kurudrive** [comment]
@mtdkei たぶんこれの事かな？

https://training.vektor-inc.co.jp/courses/x-t9-basic-settings/lessons/x-t9-sidebar-width/

**Comment by mtdkei** [comment]
@kurudrive 
そこでした！お手数をおかけしました。ありがとうございます。
