### ISSUE TITLE
色設定があるブロックでカスタムカラーの設定ができません

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/x-t9#262]
## 現状
色設定があるブロックでカスタムカラーの設定ができません。
X-T9だけでなくTT4にも起こっているので、WordPress側の問題かもしれませんが、X-T9特有の現象もあるためこちらにあげておきます。

## 不具合を確認したブロック
おそらく色設定を使うブロックならどこでも起きている可能性があります。

- Outer
- VKボタン
- ボタン
- グループ
- カバー
- コラム

## 現状
いずれの場合も現象は以下のissue通りです。
https://github.com/vektor-inc/vk-blocks-pro/issues/1948

**Comment by ChiakiKouno** [comment]
今日の社内質問会で、石川さんによるとコアの問題っぽい感じでしたね。
その後私の方でも検索してみたところ、こちらの昨年11月に上がっているIssueが近そうですが、どうかな？
https://github.com/WordPress/gutenberg/issues/56054
これは早く対応してもらいたいですねぇ…。

**Comment by mtdkei** [comment]
@kurudrive @ChiakiKouno 
ありがとうございます！動画の方法でできました！

私は日本語で分類してたのがダメだったということですかね。
![image](https://github.com/vektor-inc/x-t9/assets/21466284/236ccdd5-1999-43a4-9004-7b82fffdf5d6)

(私が今まで間違えていたことは承知で)最初色を追加するときに「色 1」と名前が出たので日本語で入力できるのかと思ったので、
- 入力時にアルファベットで"Color 1"とか出ている
- 日本語対応できている
のいずれかだったら今回も入力に手間取らないと思いました。

Chiakiさんもありがとうございます！
折を見て上記の点をGutenbergのissueにあげようかなと思います。(忘れなければですが。。)

**Comment by kurudrive** [comment]
@mtdkei いや、たぶん完了ボタンを押してなくてちゃんと登録されてなかったとかじゃないかな...
僕が試した時は 色1 色2 でもいけたので。わかんないけど（・ｗ・

**Comment by mtdkei** [comment]
@kurudrive 
確認したら、日本語のみ(マルチバイトのみ)で名前を登録したらissueの現象が起きました。
マルチバイトとシングルバイト(色1 色2)だったら動画のようになりました。
