### ISSUE TITLE
【確認待ち】[ ナビゲーションブロック ] 子階層のメニューのページを表示している時、親メニューのスタイリング

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/x-t9#27]
クラッシックテーマならメニューの先祖階層のメニュー項目に current-menu-ancestor などの識別クラスが付与される。
これが 6.0 のナビゲーションブロックではつかない。

コアの問題だが、フックでつけられるのかなど確認・対応

**Comment by shimotmk** [comment]
@kurudrive 
今のところ良いフックがなさそうです。
`render_block`や`render_block_core/navigation-submenu`のフックでうまく出来ないか試してみましたが`current-menu-item`親ブロックを指定する方法がたぶんない


コアでいくつかissues、プルリクもあるのでこれを待ったほうが良いかと思います。
https://github.com/WordPress/gutenberg/pull/40778

https://github.com/WordPress/gutenberg/issues/39663
https://github.com/WordPress/gutenberg/issues/25575

**Comment by kurudrive** [comment]
@shimotmk 調査ありがとうございます。
一旦コアの動き待ちにしましょう。

**Comment by shimotmk** [comment]
WordPress6.2で`current-menu-ancestor`のクラスが付いた様です
例：https://x-t9.vektor-inc.co.jp/docs/quick-start-import

**Comment by kurudrive** [comment]
@shimotmk おぉ！ありがとうございます！

**Comment by kurudrive** [comment]
対応確認済み close
ありがとうございました！
