### ISSUE TITLE
［6.6-RC2］サイドバーがある時の編集画面で全幅のOuterが左に寄る

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/x-t9#283]
編集画面でサイドバーを出し、Outerを全幅にすると、編集画面の左側によります。通常幅では寄りません。
なお、以下の画像は https://patterns.vektor-inc.co.jp/vk-patterns/architect-recruit/ のパターンをコピペしています。

## 6.5.5
![image](https://github.com/vektor-inc/x-t9/assets/21466284/e6704c80-9bfe-4cff-8e75-c4be65094fbf)

## 6.6
![image](https://github.com/vektor-inc/x-t9/assets/21466284/1ad4b5a8-8abf-4f1a-87cc-57bca1db829c)

**Comment by mtdkei** [comment]
修正されているようでしたのでCloseします。

**Comment by kurudrive** [comment]
@mtdkei こちらも 1.26.0 問題ないかとー。

**Comment by mtdkei** [comment]
@kurudrive
ご対応ありがとうございます。テキストが見切れないことを確認しました。
こちらはCloseします。
