### ISSUE TITLE
［6.6-RC2］サイドバーがある時の編集画面で全幅のカバーのテキストが左に見切れる

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/x-t9#284]
編集画面でサイドバーを出し、カバーを全幅にすると、テキストが左側に見切れます。通常幅では見切れません。
なお、以下の画像は https://patterns.vektor-inc.co.jp/vk-patterns/architect_interview/ のパターンをコピペしています。

## 6.5.5
![image](https://github.com/vektor-inc/x-t9/assets/21466284/63bccc3d-29f5-4177-af6c-3833f04490e1)

## 6.6
![image](https://github.com/vektor-inc/x-t9/assets/21466284/ccd75abb-6e21-4839-9873-fb2ea6fd4584)

**Comment by kurudrive** [comment]
@mtdkei おそらく 1.26.0 で問題ないかとー。

**Comment by mtdkei** [comment]
@kurudrive 
ご対応ありがとうございます。テキストが見切れないことを確認しました。
こちらCloseします。

**Comment by mtdkei** [comment]
@kurudrive 
ご対応ありがとうございます。テキストが見切れないことを確認しました。
こちらはCloseします。
