### ISSUE TITLE
［6.6-RC3］外観 > エディター > テンプレートを開くと「エディターで予期しないエラーが発生しました。」が出る

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/x-t9#287]
X-T9 Pro クイックスタートでサイトを構築した後、外観 > エディター > テンプレートを開くと「エディターで予期しないエラーが発生しました。」が出るようになりました。
![image](https://github.com/user-attachments/assets/a579fc86-a0a5-46fc-98ad-7cc1ea71e5df)

## 確認したこと
以下を確認しましたが「エディターで予期しないエラーが発生しました。」が変わらず出ます。
- Groupブロックにリンクを入れたのが原因かと思い、リンク設定をしていない状態の時のstyle.jsで確認。
- ブロックに「コンテンツ」しかないテンプレート「ブランク」で確認。

## エラーが出ない場面

- サイドバーの設定タブを出さない時はエラーになりません。(サイドバーを開いた瞬間エラーになる。)
![image](https://github.com/user-attachments/assets/2f6f3460-122c-47e3-9173-8e3d984f629c)
- エラーの状態でも画面幅をスマホくらいに縮めたらエラーが解消されます。
![image](https://github.com/user-attachments/assets/04eadd9f-34a9-42af-9b69-3ce48972028b)
-  投稿や固定ページ、カスタム投稿タイプではエラーになりません。
- 6.5.5ではエラーになりません。

**Comment by kurudrive** [comment]
@mtdkei VK Block Patterns 最新バージョンでも出る？

**Comment by mtdkei** [comment]
@kurudrive アップデートしたら出なくなりました。お手数をおかけしました、ありがとうございます。
こんなこともあるのですね。

**Comment by kurudrive** [comment]
@mtdkei いや、VK Block Patterns 先日直したのよ（・ｗ・；
