### ISSUE TITLE
コアブロックの拡張でstyle.scssを使用しているブロックではフロントエンドにCSSが反映されない

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/x-t9#291]
VK Blocks Proにコアブロックの拡張機能を追加していますが、その中でstyle.scssを使用しているブロックで、かつ「分割読み込み」をONにしているとフロントエンドにCSSが反映されません。

## 対象のコアブロック
- 見出し
- 画像
- テーブル

## 現象の条件
上記のブロックにスタイルを設定すると、編集画面ではこう見えますが、
![image](https://github.com/user-attachments/assets/9892c145-8baa-4f5c-a020-10c78111f647)

フロントエンドでは反映されません。CSSの設定が負けているとかではなく、そもそもCSSの出力がされていないような状況です。
![image](https://github.com/user-attachments/assets/5be9014f-5c15-431e-ba1d-b6b66d9b2310)

style.jsを使用しているブロック(例えばリストブロック)では同じようにスタイルを設定すると正常にフロントエンドでもデザインが反映されます。
![image](https://github.com/user-attachments/assets/c6e12b86-a58c-4331-bb8f-f52069066ee3)

## スクリーンショット
編集画面
![image](https://github.com/user-attachments/assets/806049d5-30eb-461c-b234-e5c524b2f185)

フロントエンド
![image](https://github.com/user-attachments/assets/fdcb4fd2-3a8a-48da-b701-e1238856932d)

**Comment by kurudrive** [comment]
@mtdkei これは X-T9 だからというより分割読み込みを有効にしてあるかどうかの違いとかではなくて？

**Comment by mtdkei** [comment]
@kurudrive 
> これは X-T9 だからというより分割読み込みを有効にしてあるかどうかの違いとかではなくて？
ありがとうございます。そのようでした。VK Blocks Proにissueを移動します。

**Comment by mtdkei** [comment]
以下にissueを移動したのでClose
https://github.com/vektor-inc/vk-blocks-pro/issues/2123
