### ISSUE TITLE
[編集画面] グループのパディング設定で数値の入力欄が狭い

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/x-t9#301]
グループのパディング設定などで 数値欄が狭くて見づらい場合がある
選択できる単位のなかに文字列が多いの(dvmaxなど長い単位)があるため そのぶん数値欄が狭くなっている

![padding-unit](https://github.com/user-attachments/assets/0599aa68-b3f9-4d98-9e7d-5672dcb16972)

**Comment by sysbird** [comment]
Lightning [[ 編集画面 ] パディング設定で数値欄が狭くて見づらいのを修正 #1192 ](https://github.com/vektor-inc/lightning/pull/1192)
と同じ原因ですが、同じ修正を加えても反映されない件

**Comment by mtdkei** [comment]
@sysbird 
ありがとうございます！
いまさっきX-T9でグループのパディング設定などの数値入力欄を見てみたのですが、6.7では狭い部分が解消されているかもしれません。(もしかしたらそのちょっと前から解消されてるのかもしれません。)
![image](https://github.com/user-attachments/assets/3f8c9efb-e625-4675-bf22-be511f405f84)

**Comment by sysbird** [comment]
@mtdkei 
確認ありがとうございます
私のローカル環境では、WP6.6、6.7 とも狭いままで見えます

**Comment by mtdkei** [comment]
@sysbird 
そうなのですね、ありがとうございます。
どのブロックのパディングなどでも同じ感じでしょうかね？
他の方にもご確認いただけたらと思います。

**Comment by kurudrive** [comment]
@sysbird @mtdkei 
下記で確認する限りは問題なさそうです（・ｗ・
https://demo.dev3.biz/x-t9/
vektor

@sysbird 
CSS関連の不具合らしきものをみつけた場合は、最初の調査はなるべく自身でおこなって、調査してみたけどわからない or 他の環境で再現するか確認したい場合に他の人にヘルプを求める感じでよろしくお願いいたします (￣人￣)

**Comment by sysbird** [comment]
https://demo.dev3.biz/x-t9/  で確認しても同じ状況(狭いまま)です
こちら調査して原因をつきとめて Lightning では対応しております
x-t9 では同じ対応で解決しなかったむね、本 Issue に記載してます

ですが、WP6.7 で自然解決したということでしょうかね？
でしたら もしかしたら Lightning の修正箇所も再確認して元に戻す必要がありそうですね
申しわけありませんが、私のローカル環境(複数 /  キャッシュは削除済み) で解決が確認できないため、どなたか確認お願いできますか

**Comment by kurudrive** [comment]
@sysbird 確認ありがとうございます (￣人￣)

> https://demo.dev3.biz/x-t9/ で確認しても同じ状況(狭いまま)です

僕が確認しても大丈夫という事は

* ブロックなど使用条件によって発生する場合と発生しない場合がある
* ブラウザなどに起因している

のどちらかかもしれませんね 🤔

* 他のブラウザだとどうでしょう？
* 拡大表示などになっていたりしませんか？
* ↓だとどうでしょう？

https://demo.dev3.biz/x-t9/wp-admin/post.php?post=783&action=edit

![スクリーンショット 2024-11-22 15 07 46](https://github.com/user-attachments/assets/d4d12eda-f499-4615-b07c-6fbb671dcd1e)

**Comment by sysbird** [comment]
@kurudrive 
お手数おかけしておそれいります

* 確認しているのはグループブロックです
* ブラウザは Firefox と Chrome で確認しています
* 拡大表示してないです
* WPは6.6 と 6.7 と別のローカル環境です
* ご指定の記事の編集画面で段落をブロックで囲いながら確認しました(保存はしてません)
* キャッシュは削除しています

**Comment by sysbird** [comment]
別件でも再現しない issue がありますので、私の環境( 複数ですけど)がおかしい可能性が高いですね
@kurudrive さんと @mtdkei さんが表示できているのでしたら、本 issue は closeで差し支えないです

**Comment by kurudrive** [comment]
@sysbird Lightning だと発生しないんですよね？

**Comment by sysbird** [comment]
@kurudrive 
はい、Lightning では明示的に対応した経緯がありますので発生しないです
 [ 編集画面 ] パディング設定で数値欄が狭くて見づらいのを修正 [#1192](https://github.com/vektor-inc/lightning/pull/1192)
 
 今回 WP6.7 がらみでコア側で自然解決したのであれば、Lightning の修正を取り消したほうがよい気がしますが、私のローカル環境では自然解決したことが確認できない状態です
 たいへんもうしわけありません

**Comment by sysbird** [comment]
@kurudrive @mtdkei 
パディングの数字が正常に見える場合と、見えない場合(本 issue)があることがわかりました
下記の状況で、これも私だけかもしれないですが
週明けに思い出されたときにでも確認していただけると助かります

* ブラウザーの開発者ツールを表示しているときは正常
*  Firefox と Chrome で発生
* ブラウザの幅には関連がない
* なんらかのタイミングで右パネルの幅が狭くなったときに発生 (→ 開発者ツールをOFFするとなぜか狭くなるので発生)
* WP 6.7 、6.6 で同じ状況です

**Comment by sysbird** [comment]
@goutetsuguma 
確認ありがとうございます
私は Chrome でも発生しており、もしかしたら長い単位を選択すると再現するかもしれないです

**Comment by kurudrive** [comment]
@sysbird ありがとうございます。いろいろ検討しましたが単位を減らす方向で調整しました！ (￣人￣)

**Comment by sysbird** [comment]
@kurudrive 
こちら、Lightning も単位を減らす方向で合わせますか？
現状でよいでしょうか？

**Comment by kurudrive** [comment]
@sysbird いやぁ、Lightning はとりあえず現状で良いですーん。

**Comment by sysbird** [comment]
承知しました
ではこちらは close します
ありがとうございました！！
