### ISSUE TITLE
X-T9 PaginationのNextボタンに余白がありませんので修正

### ISSUE THREAD

**Issue by YukinobuAsakawa** [vektor-inc/x-t9#312]
## 概要
X-T9のブログ一覧ページなどで、下部に表示されるページネーションですが、
Nextボタン要素の左側の余白がないため、ここを改善できないでしょうか？

![スクリーンショット 2024-12-05 16 58 09](https://github.com/user-attachments/assets/f16d8521-c9eb-44e0-b26a-f51d616049e8)

## プルリクエストについて

不慣れですが良い機会なので、PullRequest（プルリクエスト）を作成しました。
ご確認いただけますと幸いです。
（ツッコミどころ満載と思いますが、それは許してくださいー）

https://github.com/vektor-inc/x-t9/pull/311

## 変更箇所

変更ファイル
assets/_scss/_pagenation.scss

変更箇所
margin-right:0.5em; 追加

**Comment by sysbird** [comment]
ブランチを下記に移動
https://github.com/vektor-inc/x-t9/tree/fix/pagenation/margin

**Comment by sysbird** [comment]
作業中です

**Comment by kurudrive** [comment]
@YukinobuAsakawa ありがとうございます！
対応版 1.28.0 リリースしましたので close します  (￣人￣)

**Comment by YukinobuAsakawa** [comment]
@kurudrive @sysbird @goutetsuguma 

ありがとうございます。
皆さんとてもお忙しいところ、優先的にご対応いただいていたみたいで、大変恐縮です。
私でも対応できるような、issuesの時には、またPullRequestを作って送ります。
引き続きどうぞよろしくお願いいたします。
