### ISSUE TITLE
WordPress 6.1 の新機能の色バリエーション変更機能を使ってバリエーションを作る

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/x-t9#97]
とりあえず適当に何か１色作ってみる

**Comment by kurudrive** [comment]
@doshimaf これよろしくお願いいたします！

**Comment by doshimaf** [comment]
@kurudrive 
6.1の新機能の色バリエーション変更機能がどれを指しているのか分かりませんでした。
イメージとしては、stylesディレクトリを作成してcolor のプリセットが異なるjsonファイルをルートのtheme.jsonをベースに作成するというものでしょうか？

**Comment by kurudrive** [comment]
@doshimaf これの事ですー。情報不足丸投げすみません...。🙏
https://make.wordpress.org/design/2022/09/07/tt3-default-theme-announcing-style-variation-selections/

**Comment by doshimaf** [comment]
@kurudrive 
下記のプルリクのような変更でしょうか？
カラーバリエーションの追加ということでしたので、primary、primary-hoverのカラーのみ変更しています。

https://github.com/vektor-inc/x-t9/pull/98

**Comment by kurudrive** [comment]
ありがとうございます！

- [ ] json はできるだけ色情報だけにする
- [ ] 背景色が黒のバージョンがほしいっす
